version: '3'

services:
  db:
    image: postgres:13
    restart: on-failure
    environment:
      - POSTGRES_USER=interview
      - POSTGRES_PASSWORD=interview
      - POSTGRES_DATABASE=interview
    ports:
      - 5432:5432
